### ISSUE TITLE
Classification of measurements

### ISSUE THREAD

**Issue by AlyanQ** [KelvinHong/3d_body_imputation#1]
Hello, I have been using the same parent repo to extract measurements. According to the parent author, the meaning of the measurement names were taken from BodyLabs but they do not have a website anymore. Do you know what the measurements are referring to? Thanks

**Comment by KelvinHong** [comment]
Hi Alyan, in fact I'm not sure about the exact meaning of these names, but I've added descriptions for them. Hope this helps.
